### ISSUE TITLE
DFD Medien

### ISSUE THREAD

**Issue by mostermann96** [mostermann96/SWT2#1]
Sollen die CRUD Anfragen zu Medien so, mit nur "Mediendaten" als Eingang bleiben oder wie in DFD 2 "Verwalte Nutzer" als "Anfrage zu Nutzerverwaltung", also "Anfrage zu Medienverwaltung" dargestellt werden?

**Comment by LidiaRoszko** [comment]
in DFD_1 Verwalte Nutzer und Gruppen.drawio sind: Anfragen zur Verwaltung der Nutzerdaten
also Anfragen zur Verwaltung der Mediendaten passen auch meiner Meinung nach
